### ISSUE TITLE
大佬，那个server密钥是啥呀

### ISSUE THREAD

**Issue by lzk821** [gaohan-cmd/ikuuu#2]
大佬，那个server密钥是啥呀

**Comment by gaohan-cmd** [comment]
> 大佬，那个server密钥是啥呀

应该是这个server酱密钥
https://sct.ftqq.com/sendkey
但我没用过，一般看青龙自带通知

**Comment by lzk821** [comment]
大佬，我的显示这个错误：Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import requests, json, re, os
  File "/usr/lib/python3.8/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/usr/lib/python3.8/site-packages/requests/utils.py", line 25, in <module>
    from . import certs
  File "/usr/lib/python3.8/site-packages/requests/certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'
然后我在ssh手动安装了certifi还是运行不了

**Comment by gaohan-cmd** [comment]
> 大佬，我的显示这个错误：Traceback (most recent call last): File "main.py", line 1, in import requests, json, re, os File "/usr/lib/python3.8/site-packages/requests/**init**.py", line 112, in from . import utils File "/usr/lib/python3.8/site-packages/requests/utils.py", line 25, in from . import certs File "/usr/lib/python3.8/site-packages/requests/certs.py", line 15, in from certifi import where ModuleNotFoundError: No module named 'certifi' 然后我在ssh手动安装了certifi还是运行不了

是青龙吗？可以直接在青龙面板依赖那边搜索有没有certifi，没有的话进入到容器内部pip install certifi试试

**Comment by lzk821** [comment]
谢谢您了，应该是我的青龙有问题
